baseurl = ""
languageCode = "en-us"
title = "Morales Tree Gardening"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Morales Tree Gardening"
	description = "Ventura County Landscaping, Lawn, and Tree Services"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Morales Tree Gardening"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Lawn Care That Cares"
		subtitle   = "100% Service Guarantee. Flexible Pricing. Locally Owned."


	# About section
	[params.about]
		headline    = "About Us"
		description = "We are committed to providing you with the best results in all your gardening maintenance and landscaping overhauling needs. With over 30 years of experience we have a solution right for you. Insured and licensed (Lic. #087474) to serve Ventura, Oxnard, and Camarillo."
		buttonText  = "Contact Us"


	# Service section
	[params.services]
		headline = "Our Services"

        [[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/lawn-mower.png"
            title = "Landscaping"
            description = "Our goal is to maintain your landscape looking clean, healthy, and attractive."

        [[params.services.list]]
            icon = "https://img.icons8.com/pastel-glyph/64/000000/sugar-sack--v1.png"
			title = "Fertilization"
			description = "We ensure your lawn is green year-round with both organic and synthetic fertilizer options."

		[[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/grass.png"
            title = "Weed Control"
            description = "Keep your lawn looking its best by controlling crabgrass, broadleaf, and nutsedge."

         [[params.services.list]]
            icon = "https://img.icons8.com/emoji/48/000000/deciduous-tree-emoji.png"
            title = "Trimming, Pruning, and Removal of Trees"
            description = "Our professional team can trim, prune, or completely remove trees and palms."


        [[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/garden-sprinkler.png"
            title = "Irrigation Systems"
            description = "We install, repair, and program most major brands of irrigation systems."

       
        [[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/interstate-truck.png"
            title = "Hauling Services"
            description = "Need to detach a lawn completely and re-seed? We'll handle the hauling."

        [[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/wheelbarrow.png"
            title = "Decoration"
            description = "Add decoration to your flower beds with mulch, bark, and ground cover."

         [[params.services.list]]
            icon = "https://img.icons8.com/ios-filled/50/000000/lawn-care.png"
            title = "Lawn Care"
            description = "All mowing services include string trimming & blowing of clippings scheduled on a weekly or bimonthly basis."    
       


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "805-407-9520"
		email = "contact@moralestgardening.com"
